getAppointments:
  path: /api/appointments/
  defaults: { _controller: 'App\Controller\AppointmentController::getAllAction' }
  methods: [GET]

getAppointment:
  path: /api/appointments/{id}
  defaults:  { _controller: 'App\Controller\AppointmentController::getAction' }
  methods: [GET]

createAppointment:
  path: /api/appointments/
  defaults: { _controller: 'App\Controller\AppointmentController::createAction' }
  methods: [POST]

deleteAppointment:
  path: /api/appointments/{id}
  defaults: { _controller: 'App\Controller\AppointmentController::deleteAction' }
  methods: [DELETE]


#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
