getAppointments:
  path: /api/appointments/
  defaults: { _controller: 'App\Controller\AppointmentController::getAllAction' }
  methods: [GET]

getAppointment:
  path: /api/appointments/{id}
  defaults:  { _controller: 'App\Controller\AppointmentController::getAction' }
  methods: [GET]

createAppointment:
  path: /api/appointments/
  defaults: { _controller: 'App\Controller\AppointmentController::createAction' }
  methods: [POST]

updateAppointment:
  path: /api/appointments/{id}
  defaults: { _controller: 'App\Controller\AppointmentController::updateAction' }
  methods: [PUT]

deleteAppointment:
  path: /api/appointments/{id}
  defaults: { _controller: 'App\Controller\AppointmentController::deleteAction' }
  methods: [DELETE]
